### Câu hỏi tự đặt ra: User nào có tầm ảnh hưởng lớn nhất trong thể loại nhạc EDM (Electronic dance music) hiện tại trên Soundcloud

## Bước 0: Khai báo các biến và thư viện

In [1]:
import numpy as np
import pandas as pd

In [2]:
playlist_df = pd.read_csv("./playlist.csv")
track_df= pd.read_csv("./track.csv")
user_df = pd.read_csv("./user.csv")
del user_df['Unnamed: 0']
del track_df['Unnamed: 0']
del playlist_df['Unnamed: 0']

## Bước 1: Kiểm tra dữ liệu

In [3]:
#Liệt kê 5 dòng đầu của dataframe
track_df.head()

,Unnamed: 0,link_singer_belong,name_of_track,link_playlist_belong,uploaded_time,number_of_plays,number_of_repost,number_of_comment
0,0,https://soundcloud.com/skrillex,Skrillex - Kyoto feat Sirah,https://soundcloud.com/demetp/sets/edm,8 May 2012,"185,670","20,539","8,135"
1,1,https://soundcloud.com/davidguetta,Memories (feat. Kid Cudi),https://soundcloud.com/demetp/sets/edm,21 August 2009,"6,042",228,NaN
2,2,https://soundcloud.com/officialswedishhousemafia,Save The World,https://soundcloud.com/demetp/sets/edm,1 January 2011,783,21,NaN
3,3,https://soundcloud.com/ingrosso,Calling (Lose My Mind) (Radio Edit) [feat. Rya...,https://soundcloud.com/demetp/sets/edm,1 January 2012,684,22,NaN
4,4,https://soundcloud.com/olav-basoski,Bingo Players - Cry Just A Little - Olav Basos...,https://soundcloud.com/demetp/sets/edm,9 December 2013,278,37,3

In [4]:
#Liệt kê tất cả các cột
for column in track_df.columns:
    print(column)

Unnamed: 0
link_singer_belong
name_of_track
link_playlist_belong
uploaded_time
number_of_plays
number_of_repost
number_of_comment

In [5]:
#Liệt kê thông tin của data frame track
track_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            162 non-null    int64
 1   link_singer_belong    149 non-null    object
 2   name_of_track         139 non-null    object
 3   link_playlist_belong  143 non-null    object
 4   uploaded_time         143 non-null    object
 5   number_of_plays       162 non-null    object
 6   number_of_repost      162 non-null    object
 7   number_of_comment     76 non-null     object
dtypes: int64(1), object(7)
memory usage: 10.2+ KB

In [6]:
#Liệt kê 5 dòng đầu của dataframe playlist_df
playlist_df.head()

,Unnamed: 0,title,name_of_user_owner,link_of_user_owner,uploaded_time,number_of_tracks,duration_of_all_tracks,number_of_likes
0,0,EDM,demetp,https://soundcloud.com/demetp,12 April 2020,496,35:29:26,3

In [7]:
#Liệt kê tên cột của column
for column in playlist_df.columns:
    print(column)

Unnamed: 0
title
name_of_user_owner
link_of_user_owner
uploaded_time
number_of_tracks
duration_of_all_tracks
number_of_likes

In [8]:
#Liệt kê thông tin của dataframe playlist
playlist_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1 non-null      int64
 1   title                   1 non-null      object
 2   name_of_user_owner      1 non-null      object
 3   link_of_user_owner      1 non-null      object
 4   uploaded_time           1 non-null      object
 5   number_of_tracks        1 non-null      int64
 6   duration_of_all_tracks  1 non-null      object
 7   number_of_likes         1 non-null      int64
dtypes: int64(3), object(5)
memory usage: 192.0+ bytes

In [9]:
#Liệt kê 5 dòng đầu của data frame user
user_df.head()

,Unnamed: 0,name,support_name,location,number_of_follower,numbert_of_following,number_of_tracks,number_of_likes,number_of_commets,link_of_user_owner
0,0,demetp,"Tallmadge, United States",NaN,4,5,0,25,NaN,https://soundcloud.com/demetp
1,1,Skrillex Pro Unlimited,Sonny Moore,"Los Angeles, United States",6.47M,95,106,13,9,https://soundcloud.com/skrillex
2,2,David Guetta Pro Unlimited,David Guetta,"Paris, France",2.36M,7,617,NaN,NaN,https://soundcloud.com/davidguetta
3,3,Swedish House Mafia Pro Unlimited,Sweden,NaN,728K,0,63,NaN,NaN,https://soundcloud.com/officialswedishhousemafia
4,4,Sebastian Ingrosso,Sweden,NaN,3.39M,11,66,23,NaN,https://soundcloud.com/ingrosso

In [10]:
#Liệt kê các cột trong dataframe User
for column in user_df.columns:
    print(column)

Unnamed: 0
name
support_name
location
number_of_follower
numbert_of_following
number_of_tracks
number_of_likes
number_of_commets
link_of_user_owner

In [11]:
#In ra thông tin của user df
user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            114 non-null    int64
 1   name                  114 non-null    object
 2   support_name          97 non-null     object
 3   location              58 non-null     object
 4   number_of_follower    113 non-null    object
 5   numbert_of_following  113 non-null    object
 6   number_of_tracks      113 non-null    object
 7   number_of_likes       92 non-null     object
 8   number_of_commets     73 non-null     object
 9   link_of_user_owner    114 non-null    object
dtypes: int64(1), object(9)
memory usage: 9.0+ KB

**Check for NaN values**

In [12]:
#In ra các trường Nan có trong bảng playlist
playlist_df.isna().sum()

Unnamed: 0                0
title                     0
name_of_user_owner        0
link_of_user_owner        0
uploaded_time             0
number_of_tracks          0
duration_of_all_tracks    0
number_of_likes           0
dtype: int64

In [13]:
#In ra các trường Nan trong bảng Track
track_df.isna().sum()

Unnamed: 0               0
link_singer_belong      13
name_of_track           23
link_playlist_belong    19
uploaded_time           19
number_of_plays          0
number_of_repost         0
number_of_comment       86
dtype: int64

In [14]:
#In ra các trường Nan trong bảng Track
user_df.isna().sum()

Unnamed: 0               0
name                     0
support_name            17
location                56
number_of_follower       1
numbert_of_following     1
number_of_tracks         1
number_of_likes         22
number_of_commets       41
link_of_user_owner       0
dtype: int64

# Step 2 - Cleaning data

In [15]:
#Làm đầy dữ liệu với những trường NaN trong dữ liệu
user_df['number_of_commets'] = user_df['number_of_commets'].fillna(0)
user_df = user_df[user_df['number_of_tracks'].notna()]
user_df = user_df[user_df['numbert_of_following'].notna()]
user_df = user_df[user_df['number_of_follower'].notna()]
user_df['number_of_likes'] = user_df['number_of_likes'].fillna(0)
track_df.dropna(subset=['name_of_track','link_singer_belong'], inplace=True)

In [16]:
#Kiểm tra lại bảng User
user_df.isna().sum()

Unnamed: 0               0
name                     0
support_name            17
location                56
number_of_follower       0
numbert_of_following     0
number_of_tracks         0
number_of_likes          0
number_of_commets        0
link_of_user_owner       0
dtype: int64

In [17]:
#Kiểm tra số dòng trùng trong bảng
duplicate_playlist = playlist_df[playlist_df.duplicated(['link_of_user_owner'])]
duplicate_track = track_df[track_df.duplicated(['name_of_track','link_singer_belong'])]
duplicate_user = user_df[user_df.duplicated(['link_of_user_owner'])]
print(f'Số dòng trùng trong bảng Playlist: {len(duplicate_playlist)}')
print(f'Số dòng trùng trong bảng Track: {len(duplicate_track)}')
print(f'Số dòng trùng trong bảng User: {len(duplicate_user)}')

Số dòng trùng trong bảng Playlist: 0
Số dòng trùng trong bảng Track: 0
Số dòng trùng trong bảng User: 0

In [33]:
#Lấp đầy bảng User
user_df['support_name'] = user_df['support_name'].fillna('')
user_df['location'] = user_df['location'].fillna('')

**Ngay từ bước xử lí data em đã rất cố gắng để có thể hạn chế tối đa sự trùng lặp trong dữ liệu để hạn chế việc xử lí quá dư thừa ảnh hưởng đến tiến độ. Nên dữ liệu thu được có tỉ lệ trùng lặp gần như bằng 0.**

In [27]:
def process_number_string(num):
    num = str(num)
    num = num.replace(',', '')
    if num[-1]=='M':
        return float(num[:-1])*1000000
    elif num[-1]=='K':
        return float(num[:-1])*1000
    else:
        return float(num)

In [31]:
user_df.head()

,Unnamed: 0,name,support_name,location,number_of_follower,numbert_of_following,number_of_tracks,number_of_likes,number_of_commets,link_of_user_owner
0,0,demetp,"Tallmadge, United States",NaN,4.0,5.0,0.0,0.0,0.0,https://soundcloud.com/demetp
1,1,Skrillex Pro Unlimited,Sonny Moore,"Los Angeles, United States",6470000.0,95.0,106.0,106.0,9.0,https://soundcloud.com/skrillex
2,2,David Guetta Pro Unlimited,David Guetta,"Paris, France",2360000.0,7.0,617.0,617.0,0.0,https://soundcloud.com/davidguetta
3,3,Swedish House Mafia Pro Unlimited,Sweden,NaN,728000.0,0.0,63.0,63.0,0.0,https://soundcloud.com/officialswedishhousemafia
4,4,Sebastian Ingrosso,Sweden,NaN,3390000.0,11.0,66.0,66.0,0.0,https://soundcloud.com/ingrosso

**Convert tất cả các trường có trong bảng sang dạng float**

In [32]:
df = user_df
df['number_of_follower'] =df['number_of_follower'].apply(process_number_string)
df['numbert_of_following'] = df['numbert_of_following'].apply(process_number_string)
df['number_of_tracks'] = df['number_of_tracks'].apply(process_number_string)
df['number_of_likes'] = df['number_of_tracks'].apply(process_number_string)
df['number_of_commets'] = df['number_of_commets'].apply(process_number_string)
user_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113 entries, 0 to 113
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            113 non-null    int64
 1   name                  113 non-null    object
 2   support_name          96 non-null     object
 3   location              57 non-null     object
 4   number_of_follower    113 non-null    float64
 5   numbert_of_following  113 non-null    float64
 6   number_of_tracks      113 non-null    float64
 7   number_of_likes       113 non-null    float64
 8   number_of_commets     113 non-null    float64
 9   link_of_user_owner    113 non-null    object
dtypes: float64(5), int64(1), object(4)
memory usage: 9.7+ KB

In [63]:
df = track_df
df['number_of_plays'] =df['number_of_plays'].apply(process_number_string)
df['number_of_repost'] = df['number_of_repost'].apply(process_number_string)
df['number_of_comment'] = df['number_of_comment'].apply(process_number_string)
user_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113 entries, 0 to 113
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   name                             113 non-null    object
 1   support_name                     113 non-null    object
 2   location                         113 non-null    object
 3   number_of_follower               113 non-null    float64
 4   numbert_of_following             113 non-null    float64
 5   number_of_tracks                 113 non-null    float64
 6   number_of_likes                  113 non-null    float64
 7   number_of_commets                113 non-null    float64
 8   link_of_user_owner               113 non-null    object
 9   number_of_repost                 113 non-null    int64
 10  number_of_plays_from_all_tracks  113 non-null    int64
dtypes: float64(5), int64(2), object(4)
memory usage: 10.6+ KB

## Step 3 - EDA

### Mở rộng trường dữ liệu bằng cách kết hợp dữ liệu của tất cả các bảng lại với nhau

In [39]:
del user_df['Unnamed: 0']

In [46]:
track_df.head(1)

,Unnamed: 0,link_singer_belong,name_of_track,link_playlist_belong,uploaded_time,number_of_plays,number_of_repost,number_of_comment
0,0,https://soundcloud.com/skrillex,Skrillex - Kyoto feat Sirah,https://soundcloud.com/demetp/sets/edm,8 May 2012,"185,670","20,539","8,135"

In [43]:
playlist_df.head(1)

,Unnamed: 0,title,name_of_user_owner,link_of_user_owner,uploaded_time,number_of_tracks,duration_of_all_tracks,number_of_likes
0,0,EDM,demetp,https://soundcloud.com/demetp,12 April 2020,496,35:29:26,3

In [61]:
#Số lượng repost của tất cả các tracks mà User sở hữu
def find_number_of_repost_from_track(link_user):
    return len(track_df[track_df['link_singer_belong'] == link_user])
user_df['number_of_repost_from_tracks'] = user_df['link_of_user_owner'].apply(find_number_of_repost_from_track)
user_df.head()

,name,support_name,location,number_of_follower,numbert_of_following,number_of_tracks,number_of_likes,number_of_commets,link_of_user_owner,number_of_repost
0,demetp,"Tallmadge, United States",,4.0,5.0,0.0,0.0,0.0,https://soundcloud.com/demetp,0
1,Skrillex Pro Unlimited,Sonny Moore,"Los Angeles, United States",6470000.0,95.0,106.0,106.0,9.0,https://soundcloud.com/skrillex,2
2,David Guetta Pro Unlimited,David Guetta,"Paris, France",2360000.0,7.0,617.0,617.0,0.0,https://soundcloud.com/davidguetta,1
3,Swedish House Mafia Pro Unlimited,Sweden,,728000.0,0.0,63.0,63.0,0.0,https://soundcloud.com/officialswedishhousemafia,5
4,Sebastian Ingrosso,Sweden,,3390000.0,11.0,66.0,66.0,0.0,https://soundcloud.com/ingrosso,3

In [65]:
def process_number_string_1(num):
    num = str(num)
    num = num.replace(',', '')
    if num[-1]=='M':
        return float(num[:-1])*1000000
    elif num[-1]=='K':
        return float(num[:-1])*1000
    else:
        return float(num)
def find_number_of_play_from_track(link_user):    
    tmp_rows = track_df[track_df['link_singer_belong'] == link_user]
    return tmp_rows['number_of_plays'].sum()
user_df['number_of_plays_from_all_tracks'] = user_df['link_of_user_owner'].apply(find_number_of_play_from_track)
user_df.head()

,name,support_name,location,number_of_follower,numbert_of_following,number_of_tracks,number_of_likes,number_of_commets,link_of_user_owner,number_of_repost,number_of_plays_from_all_tracks
0,demetp,"Tallmadge, United States",,4.0,5.0,0.0,0.0,0.0,https://soundcloud.com/demetp,0,0.0
1,Skrillex Pro Unlimited,Sonny Moore,"Los Angeles, United States",6470000.0,95.0,106.0,106.0,9.0,https://soundcloud.com/skrillex,2,411235.0
2,David Guetta Pro Unlimited,David Guetta,"Paris, France",2360000.0,7.0,617.0,617.0,0.0,https://soundcloud.com/davidguetta,1,6042.0
3,Swedish House Mafia Pro Unlimited,Sweden,,728000.0,0.0,63.0,63.0,0.0,https://soundcloud.com/officialswedishhousemafia,5,2810.0
4,Sebastian Ingrosso,Sweden,,3390000.0,11.0,66.0,66.0,0.0,https://soundcloud.com/ingrosso,3,19163.0

In [68]:
def find_number_of_comment_from_track(link_user):    
    tmp_rows = track_df[track_df['link_singer_belong'] == link_user]
    return tmp_rows['number_of_comment'].sum()
def get_time_from_number(num):
    return num*3.12
user_df['number_of_comment_from_all_tracks'] = user_df['link_of_user_owner'].apply(find_number_of_play_from_track)
user_df['total_of_all_track_time'] = user_df['number_of_tracks'].apply(get_time_from_number)
user_df.head()

,name,support_name,location,number_of_follower,numbert_of_following,number_of_tracks,number_of_likes,number_of_commets,link_of_user_owner,number_of_repost,number_of_plays_from_all_tracks,number_of_comment_from_all_tracks,total_of_all_track_time
0,demetp,"Tallmadge, United States",,4.0,5.0,0.0,0.0,0.0,https://soundcloud.com/demetp,0,0.0,0.0,0.00
1,Skrillex Pro Unlimited,Sonny Moore,"Los Angeles, United States",6470000.0,95.0,106.0,106.0,9.0,https://soundcloud.com/skrillex,2,411235.0,411235.0,330.72
2,David Guetta Pro Unlimited,David Guetta,"Paris, France",2360000.0,7.0,617.0,617.0,0.0,https://soundcloud.com/davidguetta,1,6042.0,6042.0,1925.04
3,Swedish House Mafia Pro Unlimited,Sweden,,728000.0,0.0,63.0,63.0,0.0,https://soundcloud.com/officialswedishhousemafia,5,2810.0,2810.0,196.56
4,Sebastian Ingrosso,Sweden,,3390000.0,11.0,66.0,66.0,0.0,https://soundcloud.com/ingrosso,3,19163.0,19163.0,205.92

### Các trường dữ liệu cần quan tâm trong bảng User sau khi thực hiện bước kết hợp thông tin từ các bảng lại với nhau
**number_of_follower**: Số người theo dõi User này <br> 
**number_of_following**: Số người đang theo dõi User này<br> 
**number_of_tracks**: Số tracks mà người này có<br> 
**number_of_likes**: Số lượt thích mà người này nhận được<br> 
**number_of_comment**: Số lượt comment mà người ngày đã đi comment<br> 
**number_of_repost**: Tổng số lượng repost của các track mà người này đã đạt được<br> 
**number_of_plays_from_all_trasks**: Tổng số lượt plays của tất cả các track mà người này sợ hữu<br> 
**number_of_comment_from_all_tracks**: Tổng số comment mà người này nhận được từ tất cả các list<br> 
**total_of_all_track_time**: Tổng số giờ nhạc của tất các tracks mà người này có